version: '3'
services:
 mysql:
   build:
    context: ./mysql
   env_file: ./mysql/mysql.env
   environment:
     - TZ=Asia/Tokyo
   ports:
     - '3306:3306'
   volumes:
     - ./mysql/conf:/etc/mysql/conf.d/:ro
     - mysqldata:/var/lib/mysql
   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   networks:
     - default
 web:
   image: node:12
   environment:
     - TZ=Asia/Tokyo
     - DEBUG=app:*
   tty: true
   ports:
     - '3000:3000'
     - '3001:3001'
   volumes:
     - ./web:/app
   working_dir: /app
    command: npm run dev
   networks:
     - default
   depends_on:
     - mysql
networks:
 default:

volumes:
 mysqldata: